config/routes.rb
RailsMdb::Application.routes.draw do
  devise_for :admins

  devise_for :users

  resources :genres

  resources :films do
    resources :comments, :only => [:create, :destroy]
  end
  
  resources :search, :only => :create
  
  root :to => "home#index"

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :films, :dependent => :destroy
  
  validates_presence_of :name
  
end

# == Schema Information
#
# Table name: genres
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(params[:genre])
    if @genre.save
      redirect_to @genre, :notice => "Successfully created genre."
    else
      render :action => 'new'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update_attributes(params[:genre])
      redirect_to @genre, :notice  => "Successfully updated genre."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_url, :notice => "Successfully destroyed genre."
  end
end

app/helpers/genres_helper.rb
module GenresHelper
  # helper method
  def genre_options
    options = Genre.all.collect do |genre| 
      [genre.name, genre.id]
    end
  end
end

app/views/genres/_form.html.erb
<%= form_for @genre do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/genres/edit.html.erb
<% title "Edit Genre" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @genre %> |
  <%= link_to "View All", genres_path %>
</p>

app/views/genres/index.html.erb
<% title "Genres" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for genre in @genres %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "Show", genre %></td>
      <td><%= link_to "Edit", edit_genre_path(genre) %></td>
      <td><%= link_to "Destroy", genre, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Genre", new_genre_path %></p>

app/views/genres/new.html.erb
<% title "New Genre" %>

<%= render 'form' %>

<p><%= link_to "Back to List", genres_path %></p>

app/views/genres/show.html.erb
<% title "Genre" %>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<p>
  <%= link_to "Edit", edit_genre_path(@genre) %> |
  <%= link_to "Destroy", @genre, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", genres_path %>
</p>