config/routes.rb
RailsMdb::Application.routes.draw do
  devise_for :admins

  devise_for :users

  resources :genres

  resources :films do
    resources :comments, :only => [:create, :destroy]
  end
  
  resources :search, :only => :create
  
  root :to => "home#index"

end

app/models/film.rb
require 'open-uri'
require 'net/http'

class Film < ActiveRecord::Base
  before_validation :clean_url #this is the name of a private method
  validates_presence_of :name, :url, :description, :genre
  validates_numericality_of :rating, :greater_than => -1, :less_than => 6   
  belongs_to :genre

  has_many :comments, :dependent => :destroy
  
  has_attached_file :photo, :styles => {:medium => "300X300>", :thumb => "100X100>"}
  
  # handle_asynchronously :scrape_price

def scrape_price
    uri = URI.parse("http://#{self.url}")
    puts uri
    document = Nokogiri::HTML(open(uri))
    pounds = document.css('#pricePounds').text.scan(/\d+/)
    pence = document.css('#pricePence').text
    self.price = BigDecimal.new("#{pounds}.#{pence}")
    self.save!
end

handle_asynchronously :scrape_price

private
  def clean_url
    self.url.gsub!('http://', '') if self.url #self.url means it only runs this validation if there is a url
  end

end



# == Schema Information
#
# Table name: films
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  url                :string(255)
#  description        :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  rating             :integer
#  genre_id           :integer
#  photo_file_name    :string(255)
#  photo_content_type :string(255)
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  
  before_filter :authenticate_admin!, :except => [:index, :show]
  
  def index
    @films = Film.all
  end

  def show
    @film = Film.find(params[:id])
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(params[:film])
    if @film.save
      redirect_to @film, :notice => "Successfully created film."
    else
      render :action => 'new'
    end
  end

  def edit
    @film = Film.find(params[:id])
  end

  def update
    @film = Film.find(params[:id])
    if @film.update_attributes(params[:film])
      redirect_to @film, :notice  => "Successfully updated film."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy
    redirect_to films_url, :notice => "Successfully destroyed film."
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for @film, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :rating %><br />
    <%= f.select :rating, (0..5) %>
  </p>
  <p>
    <%= f.label :genre %><br />
    <%= f.select :genre_id, genre_options %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/films/edit.html.erb
<% title "Edit Film" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @film %> |
  <%= link_to "View All", films_path %>
</p>

app/views/films/index.html.erb
<% title "Films" %>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Rating</th>
	<th>Genre</th>
  </tr>
  <% for film in @films %>
    <tr>
      <td><%= film.name %></td>
      <td><%= film.url %></td>
      <td><%= film.rating %></td>
	  <td><%= film.genre.name %></td>
      <td><%= link_to "Show", film %></td>
      <td><%= link_to "Edit", edit_film_path(film) %></td>
      <td><%= link_to "Destroy", film, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Film", new_film_path %></p>

app/views/films/new.html.erb
<% title "New Film" %>

<%= render 'form' %>

<p><%= link_to "Back to List", films_path %></p>

app/views/films/show.html.erb
<% title "Film" %>

<p>
  <strong>Name:</strong>
  <%= @film.name %>
</p>
<p>
  <strong>Url:</strong>
  <%= @film.url %>
</p>
<p>
  <strong>Description:</strong>
	<%= raw RedCloth.new(@film.description).to_html %>
</p>
<p>
  <strong>Rating:</strong>
  <%= @film.rating %>
</p>
<p>
  <strong>Genre:</strong>
  <%= @film.genre.name %>
</p>
<p>
  <strong>Price:</strong>
  <%= @film.price %>
</p>
<p>
  <strong>Image:</strong>
  <%= image_tag @film.photo(:medium) %>
</p>


<p>
  <%= link_to "Edit", edit_film_path(@film) %> |
  <%= link_to "Destroy", @film, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", films_path %>
</p>

<div id="comments-container">
	Comments<br/>
	<% @film.comments.each do |comment| %>
		
		<%= render :partial => 'comments/comment', :locals => {:comment => comment} %>
		
	<% end %>
	
</div>
	
<%= hidden_field_tag :film_id, @film.id %>	
	
<div id="add-comments-container">
	Add Comments<br/>
	<% form_tag nil, :id => 'add-comment-form'  do %>
		<%= text_area_tag :add_comment_text %>
	<% end %>
	<div><button id="add-comment-button">Add</button></div>
</div>