config/routes.rb
RailsMdb::Application.routes.draw do
  devise_for :admins

  devise_for :users

  resources :genres

  resources :films do
    resources :comments, :only => [:create, :destroy]
  end
  
  resources :search, :only => :create
  
  root :to => "home#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Rails App" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
	<div id="authentication">
		<%= render :partial => 'authentication/sign_in' unless user_signed_in? || admin_signed_in? %>
		<%= render :partial => 'authentication/sign_out' if user_signed_in? || admin_signed_in? %>		
	</div>
	
    <div id="container">
	  <h1>Rails App</h1>	
	
	<div>
		<div id="navigation">
			<%= link_to "Home", root_path %>
			<%= link_to "Films", films_path %>	
			<%= link_to "Genres", genres_path %>						
		</div>
		
		<div id="search">
			<% form_tag search_index_path do %>

				<%= text_field_tag :search_for %>
				<%= submit_tag 'Go!' %>

			<% end %>
		</div>	
		<br style="clear:both;">	
	</div>
	
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>

    </div>
  </body>
</html>